version: '2.1'
services:
  unrisk-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'

      USERS_URL: 'localhost'
      USERS_PORT: '3396'
      USERS_ENTRY: 'user'
      
    ports:
      - '5000:5000'
